# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0843cb4600d80c1a61ed96c9fd6ec5f270738f2fd9b2afce2f54ac787229bbf19cde1bab8e51be7dae99f3311b487bd80e1d1bfdb85edc4b4551dd28d3d538b9

test:
  secret_key_base: 000c4c1016dcea479099ef005ac9ca0dfed9ad5ac91b6d6196301b3f0eed43848de769a122458f7328cf6164a31f9e65e570accdcc6768d822bab804a0ab1faf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
